In [1]:
##################### Section 5.4 (Modelling only)#####################

#Codes for figure are in the file 'Section 6.ipynb'

import pandas as pd
import numpy as np
import os
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import quandl
import scipy.optimize as sco
import time

path = '/Users/heshan/Desktop/Portfolio Optimization/'
os.chdir(path)

# Import price data
data_aapl = pd.read_csv('AAPL.csv')
data_goog = pd.read_csv('GOOG.csv')
data_market = pd.read_csv('SP500.csv')

datadict = {'AAPL':data_aapl, 'GOOG':data_goog,'Market':data_market}
keylist = ['AAPL','GOOG','Market']
origin_data = pd.DataFrame(index=pd.to_datetime(data_market['Date']),\
                           columns=keylist)
for key in keylist:
    data = datadict[key]
    data.index = pd.to_datetime(data['Date'])
    origin_data[key] = data['Adj Close']
prices = origin_data.copy()

# Calculate returns
returns = prices.pct_change()
returns.dropna(inplace=True)
returns_all = returns.copy()
returns.head()

AAPL      GOOG    Market
Date                                    
2014-07-15 -0.011716 -0.000154 -0.001932
2014-07-16 -0.005665 -0.003625  0.004201
2014-07-17 -0.017831 -0.015326 -0.011834
2014-07-18  0.014395  0.037213  0.010265
2014-07-21 -0.005189 -0.009427 -0.002320

# Section 5.4 Function of G-learning with linear dynamics

In [2]:
# Get beta in CAPM model
def get_beta(Y,X):
    X = sm.add_constant(X)
    model = sm.OLS(Y,X).fit()
    return model.params[1]

In [3]:
# Function to run the G learning with linear dynamics
def G_learning_with_linear_dynamics(start, end, data, rf, gamma, beta,\
                                    iterations):
    # Locate data
    returns = data.iloc[start:end,]
    T = len(returns.index)
    
    # Set some constants for convenience
    I = np.identity(N)
    In = np.concatenate((I,-I))
    
    # Initialize A_0, A_1, \Sigma, \bar{X}, \bar{a}
    A0t = []
    A1t = []
    sigmaat = []

    xbar = []
    abar = []
    dxt = []
    dat = []

    for t in range(T):
        A0t.append(np.zeros(shape=(2*N,1)))
        A1t.append(np.zeros(shape=(2*N,N)))
        sigmaat.append(np.diag(np.array([1]*(2*N))))

        xbar.append(np.array([[1/N]]*N))
        abar.append(np.array(A0t[0]+np.dot(A1t[0],xbar[t])))
        dxt.append(np.array([[0]]*N))
        dat.append(np.array([[0]]*(2*N)))
    
    # Terminal condition
    duT = -xbar[T-2]-np.dot(In.T,abar[T-1])
    dat[T-1]=np.concatenate([np.maximum(duT,np.array([[0]]*N)),\
                             np.maximum(-duT,np.array([[0]]*N))])
    
    # Initialize market signal z, returns r
    z = np.array([returns['Market']-rf]*N).T
    r = np.array(returns[keylist[0:N]]-rf)
    zt = []
    rt = []
    for t in range(T):
        zt.append((z[t,:].reshape((N,1))))
        rt.append((r[t,:].reshape((N,1))))
    
    # Get beta in CAPM model
    beta_list = np.array([])
    for key in keylist[0:N]:
        beta_list = np.append(beta_list,\
                              get_beta(data.iloc[start:end,][key],\
                              data.iloc[start:end,]['Market']))
    # Make assumptions on W, M
    W = np.diag(beta_list)
    M = np.identity(N)*1e-10
    
    # Error epsilon of CAPM model
    epsilon = r.copy()
    for i in range(N):
        epsilon[:,i] = r[:,i] - beta_list[i]*z[:,i]
    sigmat = np.cov(epsilon.T)
    
    # Further assumptions on the penalty parameters
    lambd = 1
    thetap = np.array([[0.1]]*N)
    thetan = np.array([[0.1]]*N)
    psi = np.array([[0.1]]*N)
    kp = np.array([[0.0]])
    kn = np.array([[0.0]])
    
    # Parameters related to the penalized return
    Raat_tilda = []
    Rxxt_tilda = []
    Raxt_tilda = []
    Rat_tilda = []
    Rxt_tilda = []
    for t in range(T):
        Raat_tilda.append\
            (np.concatenate((np.concatenate((-M-lambd*sigmat,\
                                             M+lambd*sigmat),axis=1),\
                             np.concatenate((M+lambd*sigmat,\
                                             -M-lambd*sigmat),axis=1))\
                            ,axis=0))
        Rxxt_tilda.append(-lambd*sigmat)
        Raxt_tilda.append(np.concatenate((-M-2*lambd*sigmat-thetap,\
                                          M+2*lambd*sigmat-thetan),\
                                         axis=0))
        Rat_tilda.append(np.concatenate((np.dot(W,zt[t])-\
                                         kp,np.dot(W,zt[t])-kn),\
                                        axis=0))
        Rxt_tilda.append(np.linalg.multi_dot([W-psi,zt[t]]))
    
    # Initilize parameters for parametrizations
    Dt = [0]*T
    Ht = [0]*T
    ft = [0]*T

    D2t = [0]*T
    H2t = [0]*T
    f2t = [0]*T

    At_hat = [0]*T
    Bt_hat = [0]*T
    Ct_hat = [0]*T

    Faat = [0]*T
    Fxxt = [0]*T
    Faxt = [0]*T
    Fat = [0]*T
    Fxt = [0]*T
    ft_hat = [0]*T

    Gaat = [0]*T
    Gxxt = [0]*T
    Gaxt = [0]*T
    Gat = [0]*T
    Gxt = [0]*T
    gt = [0]*T

    sigmaa_tilde = sigmaat.copy()
    
    # Run the loop many times
    for i in range(iterations): 

        print (beta)

        # Parametrization for R
        Raat = Raat_tilda.copy()
        Rxxt = Rxxt_tilda.copy()
        Raxt = Raxt_tilda.copy()
        Rat = []
        Rxt = []
        Rt = []
        
        for t in range(T): # (cont.) Parametrization of R
            Rat.append(Rat_tilda[t]+2*np.dot(Raat_tilda[t],abar[t])+\
                       np.dot(Raxt_tilda[t],xbar[t]))
            Rxt.append(Rxt_tilda[t]+2*np.dot(Rxxt_tilda[t],xbar[t])+\
                       np.dot(Raxt_tilda[t].T,abar[t]))
            Rt.append(np.linalg.multi_dot([abar[t].T,Raat_tilda[t],\
                                           abar[t]])+\
                      np.linalg.multi_dot([xbar[t].T,Rxxt_tilda[t],\
                                           xbar[t]])+\
                      np.linalg.multi_dot([abar[t].T,Raxt_tilda[t],\
                                           xbar[t]])+\
                      np.dot(abar[t].T,Rat_tilda[t])+\
                      np.dot(xbar[t].T,Rxt_tilda[t]))
        
        # Parameters at time T
        Dt[T-1] = Rxxt[T-1]
        Ht[T-1] = Rxt[T-1]+np.dot(Raxt[T-1].T,dat[T-1])
        ft[T-1] = np.linalg.multi_dot([dat[T-1].T,Raat[T-1],\
                                       dat[T-1]])+\
                  np.dot(dat[T-1].T,Rat[T-1])+Rt[T-1]
        
        # Backward iteration to update parametrization of 
        # G, F, E[F_{t+1}]
        for t in range(T-2,-1,-1):

            At_hat[t] = np.diag(np.diag(I+rf*I+np.dot(W,zt[t])-\
                                    np.dot(M.T,np.dot(In.T,abar[t]))))
            Bt_hat[t] = At_hat[t] - np.multiply((xbar[t]+\
                                             np.dot(In.T,abar[t])),M)
            Ct_hat[t] = np.dot(At_hat[t],xbar[t]+np.dot(In.T,abar[t]))\
                        -xbar[t+1]

            # Parametrization for E[F_{t+1}]
            Faat[t] = np.linalg.multi_dot([In, Bt_hat[t].T, Dt[t+1],\
                                           Bt_hat[t], In.T])+\
                      np.linalg.multi_dot([In,np.multiply(Dt[t+1],\
                                                      sigmat),In.T])
            Fxxt[t] = np.linalg.multi_dot([At_hat[t].T, Dt[t+1], \
                                           At_hat[t]])+\
                      np.multiply(Dt[t+1],sigmat)
            Faxt[t] = 2*np.linalg.multi_dot([In, Bt_hat[t].T,Dt[t+1],\
                                             At_hat[t]])+\
                      2*np.linalg.multi_dot([In,np.multiply(Dt[t+1],\
                                                            sigmat)])
            Fat[t] = np.linalg.multi_dot([In, Bt_hat[t].T, Ht[t+1]])+\
                     2*np.linalg.multi_dot([In, Bt_hat[t].T, Dt[t+1],\
                                            Ct_hat[t]])+\
                     2*np.linalg.multi_dot([In,np.multiply(Dt[t+1],\
                                                           sigmat),\
                                    (xbar[t]+np.dot(In.T,abar[t]))])
            Fxt[t] = np.linalg.multi_dot([At_hat[t].T, Ht[t+1]])+\
                     2*np.linalg.multi_dot([At_hat[t].T, Dt[t+1], \
                                            Ct_hat[t]])+\
                     2*np.linalg.multi_dot([np.multiply(Dt[t+1],\
                                                        sigmat),\
                                       (xbar[t]+np.dot(In.T,abar[t]))])
            ft_hat[t] = ft[t+1]+np.dot(Ct_hat[t].T,Ht[t+1])+\
                np.linalg.multi_dot([Ct_hat[t].T, Dt[t+1],Ct_hat[t]])+\
                np.linalg.multi_dot([(xbar[t]+\
                                      np.dot(In.T,abar[t])).T,\
                                     np.multiply(Dt[t+1],sigmat),\
                                     (xbar[t]+np.dot(In.T,abar[t]))])

            # Parametrization for G_t
            Gaat[t] = Raat[t]+gamma*Faat[t]
            Gxxt[t] = Rxxt[t]+gamma*Fxxt[t]
            Gaxt[t] = Raxt[t]+gamma*Faxt[t]
            Gat[t] = Rat[t]+gamma*Fat[t]
            Gxt[t] = Rxt[t]+gamma*Fxt[t]
            gt[t] = Rt[t]+gamma*ft_hat[t]

            dat_tilde = A0t[t]+np.dot(A1t[t],xbar[t]) - abar[t]
            sigmaa_tilde[t] = np.linalg.inv(sigmaat[t])-2*beta*Gaat[t]
            
            # Eigenvalue method to slove the problem of 
            # matrix inconvertibility
            max_egvalue = np.linalg.eig(Gaat[t])[0][0]
            count = 0
            while (np.linalg.det(sigmaa_tilde[t])<=0):
                if (count==0):
                    beta = abs(1/max_egvalue)
                else:
                    beta = abs(beta/max_egvalue)

                if (beta<1e-50):
                    beta = 0           
                sigmaa_tilde[t] = np.linalg.inv(sigmaat[t])-\
                                  2*beta*Gaat[t]
                count +=1

            # Parametrization for F_t
            bt = abar[t]-A0t[t]-np.dot(A1t[t],xbar[t])
            
            if beta == 0: # Special case for beta is zero
                tau = np.diag(np.array([1]*(2*N)))
                gammab = np.diag(np.array([0]*(2*N)))
                Lb = 0
            else: 
                tau = 1/beta*(np.linalg.inv(sigmaat[t])-\
                   np.linalg.multi_dot([np.linalg.inv(sigmaat[t]).T,\
                                       np.linalg.inv(sigmaa_tilde[t]),\
                                       np.linalg.inv(sigmaat[t])]))
                gammab = np.dot(np.linalg.inv(sigmaa_tilde[t]),\
                                np.linalg.inv(sigmaat[t]))
                Lb=1/(2*beta)*(np.log(np.linalg.det(sigmaat[t]))+\
                               np.log(np.linalg.det(sigmaa_tilde[t])))

            Eax = np.dot(gammab,A1t[t])+\
                  0.5*beta*np.dot(np.linalg.inv(sigmaa_tilde[t]),\
                                  Gaxt[t])
            Dax = np.dot(Gaxt[t].T,gammab)-np.dot(A1t[t].T,tau)
            Ea = np.linalg.multi_dot([A1t[t].T,gammab,Gat[t]])+\
                 beta*np.linalg.multi_dot([Gaxt[t].T,\
                                       np.linalg.inv(sigmaa_tilde[t]),\
                                       Gat[t]])
            
            # Parametrization for F_t (cont.)
            Dt[t] = Gxxt[t] + np.dot(Gaxt[t].T,Eax) - \
                    0.5*np.linalg.multi_dot([A1t[t].T, tau, A1t[t]])
            Ht[t] = Gxt[t] - np.dot(Dax,bt) + \
                    np.linalg.multi_dot([A1t[t].T,gammab,Gat[t]]) + \
                    beta*np.linalg.multi_dot([Gaxt[t].T,\
                              np.linalg.inv(sigmaa_tilde[t]),Gat[t]])
            ft[t] = gt[t] - 0.5*np.linalg.multi_dot([bt.T,tau,bt]) -\
                    np.linalg.multi_dot([Gat[t].T,gammab,bt])+\
                    beta/2*np.linalg.multi_dot([Gat[t].T,\
                            np.linalg.inv(sigmaa_tilde[t]),Gat[t]])-Lb

            # Update of mean and variance
            sigmaa2 = np.linalg.inv(sigmaa_tilde[t])
            A0t[t] = abar[t] + np.linalg.multi_dot([sigmaa2, \
                                            np.linalg.inv(sigmaat[t]),\
                                            A0t[t]-abar[t]]) + \
                                            beta*np.dot(sigmaa2,\
                                              Gat[t]-\
                                              np.dot(Gaxt[t],xbar[t]))
            A1t[t] = np.dot(sigmaa2,(np.dot(np.linalg.inv(sigmaat[t]),\
                                            A1t[t])+beta*Gaxt[t]))
            sigmaat[t] = sigmaa2

        # Forward iteration to update trajectories
        for t in range(0,T-1):
            abar[t] = A0t[t]+np.dot(A1t[t], xbar[t])

        for t in range(0,T-1):
            xbar[t+1] = np.multiply(1+rt[t],xbar[t]+\
                                    np.dot(In.T,abar[t]))
        for t in range(0,T-1):
            abar[t] = 0*abar[t]
        # Set the terminal condition again
        duT = -xbar[T-2]-np.dot(In.T,abar[T-1])
        dat[T-1]=np.concatenate([np.maximum(duT,np.array([[0]]*N)),\
                                 np.maximum(-duT,np.array([[0]]*N))])

        print (A0t[t],A1t[t])
        
    return (A0t,A1t)

# Model training

In [4]:
# Set some parameters
train_window = 63
T_all=prices.shape[0]-train_window-1
N=prices.shape[1]-1 #exclude market portfolio
rf = (1+0.02)**(1/365)-1 #Risk-free rate
gamma = 0.01
beta = 0.01
iterations = 100

In [5]:
# Tune parameters through training dataset
# First 70% data as traning set
training_data_index = int(len(returns_all.index)*0.7)
data_train = returns_all.iloc[:training_data_index,]
data_test = returns_all.iloc[training_data_index:,]
A0_list_train = []
A1_list_train = []
for i in range(int(len(data_train.index)/train_window)-1):
    start = i * train_window
    end = start + train_window
    # Run the model
    A0, A1 = G_learning_with_linear_dynamics(start, end, data_train,\
                                             rf, gamma, beta,\
                                             iterations)
    A0_list_train.append(A0)
    A1_list_train.append(A1)

/Users/heshan/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


0.01
[[-0.00018744]
 [-0.00028836]
 [-0.00016634]
 [-0.00026637]] [[-0.00100251 -0.00099994]
 [-0.00099994 -0.00100084]
 [-0.00099749 -0.00100006]
 [-0.00100006 -0.00099916]]
0.01
[[-0.00037499]
 [-0.00057682]
 [-0.00033257]
 [-0.00053263]] [[-0.00200503 -0.00199989]
 [-0.00199989 -0.00200167]
 [-0.00199497 -0.00200011]
 [-0.00200011 -0.00199833]]
0.01
[[-0.00056253]
 [-0.00086529]
 [-0.0004988 ]
 [-0.0007989 ]] [[-0.00300754 -0.00299983]
 [-0.00299983 -0.00300251]
 [-0.00299246 -0.00300017]
 [-0.00300017 -0.00299749]]
0.01
[[-0.00075007]
 [-0.00115375]
 [-0.00066503]
 [-0.00106517]] [[-0.00401005 -0.00399978]
 [-0.00399978 -0.00400335]
 [-0.00398995 -0.00400022]
 [-0.00400022 -0.00399665]]
0.01
[[-0.00093761]
 [-0.00144221]
 [-0.00083127]
 [-0.00133143]] [[-0.00501257 -0.00499972]
 [-0.00499972 -0.00500419]
 [-0.00498743 -0.00500028]
 [-0.00500028 -0.00499581]]
0.01
[[-0.00112515]
 [-0.00173067]
 [-0.0009975 ]
 [-0.0015977 ]] [[-0.00601508 -0.00599967]
 [-0.00599967 -0.00600502]
 [-0.

[[-0.00900326]
 [-0.01384741]
 [-0.00797801]
 [-0.01277956]] [[-0.0481206  -0.04799735]
 [-0.04799735 -0.04804019]
 [-0.0478794  -0.04800265]
 [-0.04800265 -0.04795981]]
0.01
[[-0.00919093]
 [-0.014136  ]
 [-0.00814411]
 [-0.01304569]] [[-0.04912312 -0.04899729]
 [-0.04899729 -0.04904103]
 [-0.04887688 -0.04900271]
 [-0.04900271 -0.04895897]]
0.01
[[-0.00937861]
 [-0.0144246 ]
 [-0.00831021]
 [-0.01331182]] [[-0.05012563 -0.04999724]
 [-0.04999724 -0.05004187]
 [-0.04987437 -0.05000276]
 [-0.05000276 -0.04995813]]
0.01
[[-0.0095663 ]
 [-0.0147132 ]
 [-0.0084763 ]
 [-0.01357795]] [[-0.05112814 -0.05099718]
 [-0.05099718 -0.05104271]
 [-0.05087186 -0.05100282]
 [-0.05100282 -0.05095729]]
0.01
[[-0.00975399]
 [-0.01500182]
 [-0.00864239]
 [-0.01384406]] [[-0.05213065 -0.05199713]
 [-0.05199713 -0.05204354]
 [-0.05186935 -0.05200287]
 [-0.05200287 -0.05195646]]
0.01
[[-0.00994169]
 [-0.01529044]
 [-0.00880846]
 [-0.01411017]] [[-0.05313316 -0.05299707]
 [-0.05299707 -0.05304438]
 [-0.05286

[[-0.01821175]
 [-0.02800096]
 [-0.01610456]
 [-0.02580769]] [[-0.09724366 -0.09699464]
 [-0.09699464 -0.09708122]
 [-0.09675634 -0.09700536]
 [-0.09700536 -0.09691878]]
0.01
[[-0.01840004]
 [-0.02829017]
 [-0.01627005]
 [-0.02607321]] [[-0.09824617 -0.09799458]
 [-0.09799458 -0.09808206]
 [-0.09775383 -0.09800542]
 [-0.09800542 -0.09791794]]
0.01
[[-0.01858835]
 [-0.02857939]
 [-0.01643552]
 [-0.02633872]] [[-0.09924868 -0.09899453]
 [-0.09899453 -0.09908289]
 [-0.09875132 -0.09900547]
 [-0.09900547 -0.09891711]]
0.01
[[-0.01877667]
 [-0.02886864]
 [-0.01660098]
 [-0.0266042 ]] [[-0.10025119 -0.09999447]
 [-0.09999447 -0.10008373]
 [-0.09974881 -0.10000553]
 [-0.10000553 -0.09991627]]
0.01
[[-1.21218052e-04]
 [-7.73639628e-05]
 [-9.96735856e-05]
 [-5.65605444e-05]] [[-0.00100168 -0.00100014]
 [-0.00100014 -0.00100204]
 [-0.00099832 -0.00099986]
 [-0.00099986 -0.00099796]]
0.01
[[-0.00024259]
 [-0.00015489]
 [-0.00019919]
 [-0.00011296]] [[-0.00200337 -0.00200028]
 [-0.00200028 -0.0020

[[-0.00558392]
 [-0.00356672]
 [-0.0045771 ]
 [-0.0025938 ]] [[-0.0460774  -0.04600642]
 [-0.04600642 -0.04609396]
 [-0.0459226  -0.04599358]
 [-0.04599358 -0.04590604]]
0.01
[[-0.0057054 ]
 [-0.00364435]
 [-0.00467651]
 [-0.0026501 ]] [[-0.04707909 -0.04700656]
 [-0.04700656 -0.047096  ]
 [-0.04692091 -0.04699344]
 [-0.04699344 -0.046904  ]]
0.01
[[-0.00582689]
 [-0.00372199]
 [-0.00477591]
 [-0.00270639]] [[-0.04808077 -0.0480067 ]
 [-0.0480067  -0.04809805]
 [-0.04791923 -0.0479933 ]
 [-0.0479933  -0.04790195]]
0.01
[[-0.00594838]
 [-0.00379963]
 [-0.00487531]
 [-0.00276267]] [[-0.04908245 -0.04900684]
 [-0.04900684 -0.04910009]
 [-0.04891755 -0.04899316]
 [-0.04899316 -0.04889991]]
0.01
[[-0.00606989]
 [-0.00387729]
 [-0.00497469]
 [-0.00281894]] [[-0.05008413 -0.05000697]
 [-0.05000697 -0.05010213]
 [-0.04991587 -0.04999303]
 [-0.04999303 -0.04989787]]
0.01
[[-0.0061914 ]
 [-0.00395494]
 [-0.00507408]
 [-0.00287521]] [[-0.05108582 -0.05100711]
 [-0.05100711 -0.05110417]
 [-0.05091

[[-0.01154852]
 [-0.00738262]
 [-0.00943618]
 [-0.00534021]] [[-0.09515983 -0.09501325]
 [-0.09501325 -0.09519401]
 [-0.09484017 -0.09498675]
 [-0.09498675 -0.09480599]]
0.01
[[-0.01167059]
 [-0.00746084]
 [-0.009535  ]
 [-0.00539591]] [[-0.09616151 -0.09601339]
 [-0.09601339 -0.09619606]
 [-0.09583849 -0.09598661]
 [-0.09598661 -0.09580394]]
0.01
[[-0.01179268]
 [-0.00753908]
 [-0.00963381]
 [-0.0054516 ]] [[-0.0971632  -0.09701353]
 [-0.09701353 -0.0971981 ]
 [-0.0968368  -0.09698647]
 [-0.09698647 -0.0968019 ]]
0.01
[[-0.01191479]
 [-0.00761734]
 [-0.00973259]
 [-0.00550727]] [[-0.09816488 -0.09801367]
 [-0.09801367 -0.09820014]
 [-0.09783512 -0.09798633]
 [-0.09798633 -0.09779986]]
0.01
[[-0.01203691]
 [-0.00769561]
 [-0.00983136]
 [-0.00556292]] [[-0.09916656 -0.09901381]
 [-0.09901381 -0.09920218]
 [-0.09883344 -0.09898619]
 [-0.09898619 -0.09879782]]
0.01
[[-0.01215905]
 [-0.0077739 ]
 [-0.00993011]
 [-0.00561855]] [[-0.10016824 -0.10001394]
 [-0.10001394 -0.10020422]
 [-0.09983

[[-0.00205441]
 [-0.00173906]
 [-0.00112591]
 [-0.00080702]] [[-0.04217755 -0.04199154]
 [-0.04199154 -0.04213304]
 [-0.04182245 -0.04200846]
 [-0.04200846 -0.04186696]]
0.01
[[-0.00210338]
 [-0.00178053]
 [-0.00115266]
 [-0.00082618]] [[-0.04318178 -0.04299134]
 [-0.04299134 -0.04313621]
 [-0.04281822 -0.04300866]
 [-0.04300866 -0.04286379]]
0.01
[[-0.00215236]
 [-0.00182199]
 [-0.0011794 ]
 [-0.00084533]] [[-0.044186   -0.04399114]
 [-0.04399114 -0.04413938]
 [-0.043814   -0.04400886]
 [-0.04400886 -0.04386062]]
0.01
[[-0.00220134]
 [-0.00186347]
 [-0.00120615]
 [-0.00086448]] [[-0.04519023 -0.04499094]
 [-0.04499094 -0.04514255]
 [-0.04480977 -0.04500906]
 [-0.04500906 -0.04485745]]
0.01
[[-0.00225032]
 [-0.00190495]
 [-0.00123288]
 [-0.00088362]] [[-0.04619445 -0.04599074]
 [-0.04599074 -0.04614571]
 [-0.04580555 -0.04600926]
 [-0.04600926 -0.04585429]]
0.01
[[-0.00229931]
 [-0.00194643]
 [-0.00125961]
 [-0.00090276]] [[-0.04719868 -0.04699054]
 [-0.04699054 -0.04714888]
 [-0.04680

[[-0.00441398]
 [-0.00373835]
 [-0.00240099]
 [-0.00171755]] [[-0.09038031 -0.08998189]
 [-0.08998189 -0.09028501]
 [-0.08961969 -0.09001811]
 [-0.09001811 -0.08971499]]
0.01
[[-0.00446343]
 [-0.00378029]
 [-0.00242727]
 [-0.00173623]] [[-0.09138453 -0.09098169]
 [-0.09098169 -0.09128817]
 [-0.09061547 -0.09101831]
 [-0.09101831 -0.09071183]]
0.01
[[-0.00451289]
 [-0.00382224]
 [-0.00245353]
 [-0.0017549 ]] [[-0.09238875 -0.09198149]
 [-0.09198149 -0.09229134]
 [-0.09161125 -0.09201851]
 [-0.09201851 -0.09170866]]
0.01
[[-0.00456236]
 [-0.00386421]
 [-0.00247977]
 [-0.00177355]] [[-0.09339298 -0.09298129]
 [-0.09298129 -0.0932945 ]
 [-0.09260702 -0.09301871]
 [-0.09301871 -0.0927055 ]]
0.01
[[-0.00461185]
 [-0.0039062 ]
 [-0.002506  ]
 [-0.00179218]] [[-0.0943972  -0.09398109]
 [-0.09398109 -0.09429767]
 [-0.0936028  -0.09401891]
 [-0.09401891 -0.09370233]]
0.01
[[-0.00466136]
 [-0.0039482 ]
 [-0.00253222]
 [-0.0018108 ]] [[-0.09540142 -0.09498088]
 [-0.09498088 -0.09530083]
 [-0.09459

[[0.00544344]
 [0.00528251]
 [0.0061665 ]
 [0.00600663]] [[-0.03804749 -0.03800186]
 [-0.03800186 -0.03804221]
 [-0.03795251 -0.03799814]
 [-0.03799814 -0.03795779]]
0.01
[[0.00558662]
 [0.00542146]
 [0.00632884]
 [0.00616476]] [[-0.03904874 -0.03900191]
 [-0.03900191 -0.03904332]
 [-0.03895126 -0.03899809]
 [-0.03899809 -0.03895668]]
0.01
[[0.0057298 ]
 [0.00556041]
 [0.00649119]
 [0.0063229 ]] [[-0.04004998 -0.04000196]
 [-0.04000196 -0.04004443]
 [-0.03995002 -0.03999804]
 [-0.03999804 -0.03995557]]
0.01
[[0.00587297]
 [0.00569934]
 [0.00665354]
 [0.00648105]] [[-0.04105123 -0.04100201]
 [-0.04100201 -0.04104554]
 [-0.04094877 -0.04099799]
 [-0.04099799 -0.04095446]]
0.01
[[0.00601614]
 [0.00583827]
 [0.0068159 ]
 [0.0066392 ]] [[-0.04205248 -0.04200205]
 [-0.04200205 -0.04204665]
 [-0.04194752 -0.04199795]
 [-0.04199795 -0.04195335]]
0.01
[[0.0061593 ]
 [0.0059772 ]
 [0.00697827]
 [0.00679736]] [[-0.04305373 -0.0430021 ]
 [-0.0430021  -0.04304776]
 [-0.04294627 -0.0429979 ]
 [-0.04

[[0.01230583]
 [0.01194162]
 [0.0139693 ]
 [0.01360749]] [[-0.08610746 -0.08600421]
 [-0.08600421 -0.08609551]
 [-0.08589254 -0.08599579]
 [-0.08599579 -0.08590449]]
0.01
[[0.01244848]
 [0.01208004]
 [0.01413217]
 [0.01376615]] [[-0.0871087  -0.08700425]
 [-0.08700425 -0.08709662]
 [-0.0868913  -0.08699575]
 [-0.08699575 -0.08690338]]
0.01
[[0.01259112]
 [0.01221845]
 [0.01429506]
 [0.01392483]] [[-0.08810995 -0.0880043 ]
 [-0.0880043  -0.08809773]
 [-0.08789005 -0.0879957 ]
 [-0.0879957  -0.08790227]]
0.01
[[0.01273374]
 [0.01235683]
 [0.01445796]
 [0.01408353]] [[-0.0891112  -0.08900435]
 [-0.08900435 -0.08909884]
 [-0.0888888  -0.08899565]
 [-0.08899565 -0.08890116]]
0.01
[[0.01287635]
 [0.0124952 ]
 [0.01462088]
 [0.01424224]] [[-0.09011245 -0.0900044 ]
 [-0.0900044  -0.09009995]
 [-0.08988755 -0.0899956 ]
 [-0.0899956  -0.08990005]]
0.01
[[0.01301893]
 [0.01263355]
 [0.01478382]
 [0.01440097]] [[-0.0911137  -0.09100445]
 [-0.09100445 -0.09110106]
 [-0.0908863  -0.09099555]
 [-0.09

[[-7.44347402e-05]
 [-5.73844127e-05]
 [ 5.90348569e-04]
 [ 6.03590903e-04]] [[-0.03415    -0.03400294]
 [-0.03400294 -0.03438865]
 [-0.03385    -0.03399706]
 [-0.03399706 -0.03361135]]
0.01
[[-7.65191185e-05]
 [-5.89633626e-05]
 [ 6.07606884e-04]
 [ 6.21234749e-04]] [[-0.03515441 -0.03500302]
 [-0.03500302 -0.03540008]
 [-0.03484559 -0.03499698]
 [-0.03499698 -0.03459992]]
0.01
[[-7.85998251e-05]
 [-6.05384253e-05]
 [ 6.24861527e-04]
 [ 6.38874709e-04]] [[-0.03615882 -0.03600311]
 [-0.03600311 -0.0364115 ]
 [-0.03584118 -0.03599689]
 [-0.03599689 -0.0355885 ]]
0.01
[[-8.06770569e-05]
 [-6.21097967e-05]
 [ 6.42112695e-04]
 [ 6.56510977e-04]] [[-0.03716323 -0.03700319]
 [-0.03700319 -0.03742292]
 [-0.03683677 -0.03699681]
 [-0.03699681 -0.03657708]]
0.01
[[-8.27510103e-05]
 [-6.36776727e-05]
 [ 6.59360584e-04]
 [ 6.74143750e-04]] [[-0.03816764 -0.03800328]
 [-0.03800328 -0.03843434]
 [-0.03783236 -0.03799672]
 [-0.03799672 -0.03756566]]
0.01
[[-8.48218817e-05]
 [-6.52422489e-05]
 [ 6.76

[[-0.0001716 ]
 [-0.00013055]
 [ 0.00140069]
 [ 0.00143181]] [[-0.0813572  -0.08100698]
 [-0.08100698 -0.08192492]
 [-0.0806428  -0.08099302]
 [-0.08099302 -0.08007508]]
0.01
[[-0.00017373]
 [-0.00013216]
 [ 0.00141799]
 [ 0.00144948]] [[-0.08236161 -0.08200707]
 [-0.08200707 -0.08293631]
 [-0.08163839 -0.08199293]
 [-0.08199293 -0.08106369]]
0.01
[[-0.00017586]
 [-0.00013377]
 [ 0.00143529]
 [ 0.00146716]] [[-0.08336602 -0.08300715]
 [-0.08300715 -0.08394771]
 [-0.08263398 -0.08299285]
 [-0.08299285 -0.08205229]]
0.01
[[-0.00017799]
 [-0.00013539]
 [ 0.0014526 ]
 [ 0.00148484]] [[-0.08437042 -0.08400724]
 [-0.08400724 -0.08495911]
 [-0.08362958 -0.08399276]
 [-0.08399276 -0.08304089]]
0.01
[[-0.00018013]
 [-0.00013701]
 [ 0.00146992]
 [ 0.00150253]] [[-0.08537483 -0.08500733]
 [-0.08500733 -0.0859705 ]
 [-0.08462517 -0.08499267]
 [-0.08499267 -0.0840295 ]]
0.01
[[-0.00018228]
 [-0.00013864]
 [ 0.00148724]
 [ 0.00152022]] [[-0.08637924 -0.08600741]
 [-0.08600741 -0.0869819 ]
 [-0.08562

[[ 6.28285785e-06]
 [-1.11479617e-05]
 [ 4.96574882e-04]
 [ 4.82146285e-04]] [[-0.02708386 -0.02700184]
 [-0.02700184 -0.0270737 ]
 [-0.02691614 -0.02699816]
 [-0.02699816 -0.0269263 ]]
0.01
[[ 6.52563849e-06]
 [-1.15508250e-05]
 [ 5.14956462e-04]
 [ 4.99993531e-04]] [[-0.02808697 -0.02800191]
 [-0.02800191 -0.02807643]
 [-0.02791303 -0.02799809]
 [-0.02799809 -0.02792357]]
0.01
[[ 6.76687988e-06]
 [-1.19552404e-05]
 [ 5.33339581e-04]
 [ 5.17842328e-04]] [[-0.02909008 -0.02900198]
 [-0.02900198 -0.02907916]
 [-0.02890992 -0.02899802]
 [-0.02899802 -0.02892084]]
0.01
[[ 7.00638746e-06]
 [-1.23614023e-05]
 [ 5.51724435e-04]
 [ 5.35692873e-04]] [[-0.03009318 -0.03000204]
 [-0.03000204 -0.03008189]
 [-0.02990682 -0.02999796]
 [-0.02999796 -0.02991811]]
0.01
[[ 7.24396656e-06]
 [-1.27695055e-05]
 [ 5.70111216e-04]
 [ 5.53545358e-04]] [[-0.03109629 -0.03100211]
 [-0.03100211 -0.03108462]
 [-0.03090371 -0.03099789]
 [-0.03099789 -0.03091538]]
0.01
[[ 7.47942239e-06]
 [-1.31797447e-05]
 [ 5.88

[[ 1.29048139e-05]
 [-3.29464134e-05]
 [ 1.30942480e-03]
 [ 1.27149756e-03]] [[-0.07122047 -0.07100483]
 [-0.07100483 -0.07119376]
 [-0.07077953 -0.07099517]
 [-0.07099517 -0.07080624]]
0.01
[[ 1.28927791e-05]
 [-3.36046559e-05]
 [ 1.32806119e-03]
 [ 1.28960018e-03]] [[-0.07222358 -0.0720049 ]
 [-0.0720049  -0.07219649]
 [-0.07177642 -0.0719951 ]
 [-0.0719951  -0.07180351]]
0.01
[[ 1.28703855e-05]
 [-3.42732703e-05]
 [ 1.34670795e-03]
 [ 1.30771318e-03]] [[-0.07322668 -0.07300497]
 [-0.07300497 -0.07319922]
 [-0.07277332 -0.07299503]
 [-0.07299503 -0.07280078]]
0.01
[[ 1.28374225e-05]
 [-3.49524672e-05]
 [ 1.36536527e-03]
 [ 1.32583676e-03]] [[-0.07422978 -0.07400504]
 [-0.07400504 -0.07420195]
 [-0.07377022 -0.07399496]
 [-0.07399496 -0.07379805]]
0.01
[[ 1.27936788e-05]
 [-3.56424579e-05]
 [ 1.38403338e-03]
 [ 1.34397113e-03]] [[-0.07523289 -0.07500511]
 [-0.07500511 -0.07520467]
 [-0.07476711 -0.07499489]
 [-0.07499489 -0.07479533]]
0.01
[[ 1.27389427e-05]
 [-3.63434541e-05]
 [ 1.40

[[0.00182212]
 [0.00130627]
 [0.00214659]
 [0.00164043]] [[-0.0170464  -0.01700626]
 [-0.01700626 -0.01705542]
 [-0.0169536  -0.01699374]
 [-0.01699374 -0.01694458]]
0.01
[[0.00192928]
 [0.00138309]
 [0.00227288]
 [0.00173694]] [[-0.01804913 -0.01800663]
 [-0.01800663 -0.01805868]
 [-0.01795087 -0.01799337]
 [-0.01799337 -0.01794132]]
0.01
[[0.00203645]
 [0.00145992]
 [0.00239916]
 [0.00183345]] [[-0.01905186 -0.019007  ]
 [-0.019007   -0.01906194]
 [-0.01894814 -0.018993  ]
 [-0.018993   -0.01893806]]
0.01
[[0.00214362]
 [0.00153674]
 [0.00252544]
 [0.00192995]] [[-0.02005459 -0.02000737]
 [-0.02000737 -0.0200652 ]
 [-0.01994541 -0.01999263]
 [-0.01999263 -0.0199348 ]]
0.01
[[0.00225079]
 [0.00161357]
 [0.00265173]
 [0.00202646]] [[-0.02105732 -0.02100774]
 [-0.02100774 -0.02106846]
 [-0.02094268 -0.02099226]
 [-0.02099226 -0.02093154]]
0.01
[[0.00235796]
 [0.0016904 ]
 [0.00277801]
 [0.00212297]] [[-0.02206005 -0.0220081 ]
 [-0.0220081  -0.02207172]
 [-0.02193995 -0.0219919 ]
 [-0.02

[[0.00696324]
 [0.00499092]
 [0.00821123]
 [0.00627584]] [[-0.06517736 -0.06502393]
 [-0.06502393 -0.06521185]
 [-0.06482264 -0.06497607]
 [-0.06497607 -0.06478815]]
0.01
[[0.0070702 ]
 [0.00506754]
 [0.00833772]
 [0.00637256]] [[-0.06618009 -0.0660243 ]
 [-0.0660243  -0.0662151 ]
 [-0.06581991 -0.0659757 ]
 [-0.0659757  -0.0657849 ]]
0.01
[[0.00717715]
 [0.00514415]
 [0.00846422]
 [0.00646929]] [[-0.06718282 -0.06702467]
 [-0.06702467 -0.06721836]
 [-0.06681718 -0.06697533]
 [-0.06697533 -0.06678164]]
0.01
[[0.00728409]
 [0.00522075]
 [0.00859073]
 [0.00656602]] [[-0.06818555 -0.06802503]
 [-0.06802503 -0.06822162]
 [-0.06781445 -0.06797497]
 [-0.06797497 -0.06777838]]
0.01
[[0.00739103]
 [0.00529734]
 [0.00871726]
 [0.00666277]] [[-0.06918827 -0.0690254 ]
 [-0.0690254  -0.06922488]
 [-0.06881173 -0.0689746 ]
 [-0.0689746  -0.06877512]]
0.01
[[0.00749795]
 [0.00537392]
 [0.00884379]
 [0.00675953]] [[-0.070191   -0.07002577]
 [-0.07002577 -0.07022813]
 [-0.069809   -0.06997423]
 [-0.06

[[0.00061594]
 [0.00073255]
 [0.00085432]
 [0.00097122]] [[-0.01304066 -0.01300327]
 [-0.01300327 -0.01302801]
 [-0.01295934 -0.01299673]
 [-0.01299673 -0.01297199]]
0.01
[[0.0006634 ]
 [0.00078898]
 [0.00091995]
 [0.00104585]] [[-0.01404378 -0.01400352]
 [-0.01400352 -0.01403016]
 [-0.01395622 -0.01399648]
 [-0.01399648 -0.01396984]]
0.01
[[0.00071086]
 [0.00084542]
 [0.00098559]
 [0.00112047]] [[-0.01504691 -0.01500377]
 [-0.01500377 -0.01503231]
 [-0.01495309 -0.01499623]
 [-0.01499623 -0.01496769]]
0.01
[[0.00075832]
 [0.00090185]
 [0.00105122]
 [0.0011951 ]] [[-0.01605004 -0.01600402]
 [-0.01600402 -0.01603447]
 [-0.01594996 -0.01599598]
 [-0.01599598 -0.01596553]]
0.01
[[0.00080579]
 [0.00095829]
 [0.00111685]
 [0.00126972]] [[-0.01705316 -0.01700428]
 [-0.01700428 -0.01703662]
 [-0.01694684 -0.01699572]
 [-0.01699572 -0.01696338]]
0.01
[[0.00085325]
 [0.00101472]
 [0.00118248]
 [0.00134435]] [[-0.01805629 -0.01800453]
 [-0.01800453 -0.01803878]
 [-0.01794371 -0.01799547]
 [-0.01

[[0.00289195]
 [0.0034391 ]
 [0.00400694]
 [0.00455552]] [[-0.06119071 -0.06101533]
 [-0.06101533 -0.06113139]
 [-0.06080929 -0.06098467]
 [-0.06098467 -0.06086861]]
0.01
[[0.00293925]
 [0.00349537]
 [0.00407274]
 [0.00463031]] [[-0.06219384 -0.06201559]
 [-0.06201559 -0.06213354]
 [-0.06180616 -0.06198441]
 [-0.06198441 -0.06186646]]
0.01
[[0.00298654]
 [0.00355163]
 [0.00413855]
 [0.00470511]] [[-0.06319696 -0.06301584]
 [-0.06301584 -0.06313569]
 [-0.06280304 -0.06298416]
 [-0.06298416 -0.06286431]]
0.01
[[0.00303382]
 [0.00360788]
 [0.00420436]
 [0.00477992]] [[-0.06420009 -0.06401609]
 [-0.06401609 -0.06413785]
 [-0.06379991 -0.06398391]
 [-0.06398391 -0.06386215]]
0.01
[[0.00308109]
 [0.00366412]
 [0.00427018]
 [0.00485474]] [[-0.06520321 -0.06501634]
 [-0.06501634 -0.06514   ]
 [-0.06479679 -0.06498366]
 [-0.06498366 -0.06486   ]]
0.01
[[0.00312836]
 [0.00372036]
 [0.00433601]
 [0.00492956]] [[-0.06620634 -0.06601659]
 [-0.06601659 -0.06614215]
 [-0.06579366 -0.06598341]
 [-0.06

[[0.00022989]
 [0.00026024]
 [0.00044472]
 [0.00047719]] [[-0.00903141 -0.00900285]
 [-0.00900285 -0.00900598]
 [-0.00896859 -0.00899715]
 [-0.00899715 -0.00899402]]
0.01
[[0.0002553 ]
 [0.00028903]
 [0.00049427]
 [0.00053034]] [[-0.0100349  -0.01000317]
 [-0.01000317 -0.01000665]
 [-0.0099651  -0.00999683]
 [-0.00999683 -0.00999335]]
0.01
[[0.00028072]
 [0.00031781]
 [0.00054381]
 [0.00058349]] [[-0.01103839 -0.01100349]
 [-0.01100349 -0.01100731]
 [-0.01096161 -0.01099651]
 [-0.01099651 -0.01099269]]
0.01
[[0.00030613]
 [0.0003466 ]
 [0.00059335]
 [0.00063664]] [[-0.01204188 -0.0120038 ]
 [-0.0120038  -0.01200798]
 [-0.01195812 -0.0119962 ]
 [-0.0119962  -0.01199202]]
0.01
[[0.00033154]
 [0.00037538]
 [0.00064289]
 [0.00068979]] [[-0.01304536 -0.01300412]
 [-0.01300412 -0.01300864]
 [-0.01295464 -0.01299588]
 [-0.01299588 -0.01299136]]
0.01
[[0.00035696]
 [0.00040417]
 [0.00069243]
 [0.00074294]] [[-0.01404885 -0.01400444]
 [-0.01400444 -0.0140093 ]
 [-0.01395115 -0.01399556]
 [-0.01

[[0.00144743]
 [0.00163947]
 [0.0028251 ]
 [0.00303093]] [[-0.05719884 -0.05701807]
 [-0.05701807 -0.05703788]
 [-0.05680116 -0.05698193]
 [-0.05698193 -0.05696212]]
0.01
[[0.00147266]
 [0.00166806]
 [0.00287483]
 [0.00308428]] [[-0.05820233 -0.05801838]
 [-0.05801838 -0.05803854]
 [-0.05779767 -0.05798162]
 [-0.05798162 -0.05796146]]
0.01
[[0.00149788]
 [0.00169665]
 [0.00292457]
 [0.00313763]] [[-0.05920582 -0.0590187 ]
 [-0.0590187  -0.05903921]
 [-0.05879418 -0.0589813 ]
 [-0.0589813  -0.05896079]]
0.01
[[0.00152309]
 [0.00172522]
 [0.00297431]
 [0.00319099]] [[-0.06020931 -0.06001902]
 [-0.06001902 -0.06003987]
 [-0.05979069 -0.05998098]
 [-0.05998098 -0.05996013]]
0.01
[[0.00154829]
 [0.00175379]
 [0.00302407]
 [0.00324436]] [[-0.06121279 -0.06101933]
 [-0.06101933 -0.06104054]
 [-0.06078721 -0.06098067]
 [-0.06098067 -0.06095946]]
0.01
[[0.00157348]
 [0.00178234]
 [0.00307384]
 [0.00329775]] [[-0.06221628 -0.06201965]
 [-0.06201965 -0.0620412 ]
 [-0.06178372 -0.06198035]
 [-0.06

[[-5.22580038e-05]
 [-5.30079327e-05]
 [ 4.80228711e-05]
 [ 4.56863022e-05]] [[-0.00500785 -0.00500429]
 [-0.00500429 -0.00500831]
 [-0.00499215 -0.00499571]
 [-0.00499571 -0.00499169]]
0.01
[[-6.27542161e-05]
 [-6.36541166e-05]
 [ 5.76720569e-05]
 [ 5.48681601e-05]] [[-0.00600942 -0.00600514]
 [-0.00600514 -0.00600997]
 [-0.00599058 -0.00599486]
 [-0.00599486 -0.00599003]]
0.01
[[-7.32485528e-05]
 [-7.42984219e-05]
 [ 6.73193670e-05]
 [ 6.40481393e-05]] [[-0.00701099 -0.007006  ]
 [-0.007006   -0.00701163]
 [-0.00698901 -0.006994  ]
 [-0.006994   -0.00698837]]
0.01
[[-8.37412144e-05]
 [-8.49410490e-05]
 [ 7.69650020e-05]
 [ 7.32264403e-05]] [[-0.00801257 -0.00800686]
 [-0.00800686 -0.00801329]
 [-0.00798743 -0.00799314]
 [-0.00799314 -0.00798671]]
0.01
[[-9.42324011e-05]
 [-9.55821982e-05]
 [ 8.66091621e-05]
 [ 8.24032635e-05]] [[-0.00901414 -0.00900771]
 [-0.00900771 -0.00901495]
 [-0.00898586 -0.00899229]
 [-0.00899229 -0.00898505]]
0.01
[[-1.04722313e-04]
 [-1.06222070e-04]
 [ 9.62

[[-0.00055743]
 [-0.00056537]
 [ 0.00051253]
 [ 0.00048776]] [[-0.05308323 -0.05304542]
 [-0.05304542 -0.05308803]
 [-0.05291677 -0.05295458]
 [-0.05295458 -0.05291197]]
0.01
[[-0.00056806]
 [-0.00057615]
 [ 0.00052232]
 [ 0.00049708]] [[-0.0540848  -0.05404628]
 [-0.05404628 -0.05408969]
 [-0.0539152  -0.05395372]
 [-0.05395372 -0.05391031]]
0.01
[[-0.0005787 ]
 [-0.00058694]
 [ 0.00053211]
 [ 0.00050641]] [[-0.05508637 -0.05504713]
 [-0.05504713 -0.05509135]
 [-0.05491363 -0.05495287]
 [-0.05495287 -0.05490865]]
0.01
[[-0.00058935]
 [-0.00059774]
 [ 0.00054192]
 [ 0.00051574]] [[-0.05608794 -0.05604799]
 [-0.05604799 -0.05609301]
 [-0.05591206 -0.05595201]
 [-0.05595201 -0.05590699]]
0.01
[[-0.00060001]
 [-0.00060855]
 [ 0.00055173]
 [ 0.00052508]] [[-0.05708951 -0.05704885]
 [-0.05704885 -0.05709467]
 [-0.05691049 -0.05695115]
 [-0.05695115 -0.05690533]]
0.01
[[-0.00061067]
 [-0.00061936]
 [ 0.00056154]
 [ 0.00053443]] [[-0.05809108 -0.0580497 ]
 [-0.0580497  -0.05809633]
 [-0.05790

[[-2.55454676e-05]
 [-2.48240748e-05]
 [-4.96214199e-06]
 [-4.26707137e-06]] [[-0.00100158 -0.001     ]
 [-0.001      -0.00100073]
 [-0.00099842 -0.001     ]
 [-0.001      -0.00099927]]
0.01
[[-5.21577337e-05]
 [-5.07165379e-05]
 [-8.85748548e-06]
 [-7.46575447e-06]] [[-0.00200316 -0.002     ]
 [-0.002      -0.00200146]
 [-0.00199684 -0.002     ]
 [-0.002      -0.00199854]]
0.01
[[-7.87686415e-05]
 [-7.66076801e-05]
 [-1.27541872e-05]
 [-1.06657585e-05]] [[-0.00300474 -0.003     ]
 [-0.003      -0.00300218]
 [-0.00299526 -0.003     ]
 [-0.003      -0.00299782]]
0.01
[[-1.05378529e-04]
 [-1.02497840e-04]
 [-1.66519091e-05]
 [-1.38667453e-05]] [[-0.00400633 -0.004     ]
 [-0.004      -0.00400291]
 [-0.00399367 -0.004     ]
 [-0.004      -0.00399709]]
0.01
[[-1.31987613e-04]
 [-1.28387233e-04]
 [-2.05504347e-05]
 [-1.70684980e-05]] [[-0.00500791 -0.005     ]
 [-0.005      -0.00500364]
 [-0.00499209 -0.005     ]
 [-0.005      -0.00499636]]
0.01
[[-1.58596110e-04]
 [-1.54276078e-04]
 [-2.44

[[-0.00119819]
 [-0.00116583]
 [-0.00017466]
 [-0.00014327]] [[-0.04507115 -0.04499996]
 [-0.04499996 -0.04503276]
 [-0.04492885 -0.04500004]
 [-0.04500004 -0.04496724]]
0.01
[[-0.00122495]
 [-0.00119188]
 [-0.0001784 ]
 [-0.00014632]] [[-0.04607273 -0.04599996]
 [-0.04599996 -0.04603349]
 [-0.04592727 -0.04600004]
 [-0.04600004 -0.04596651]]
0.01
[[-0.00125172]
 [-0.00121793]
 [-0.00018214]
 [-0.00014935]] [[-0.04707431 -0.04699996]
 [-0.04699996 -0.04703422]
 [-0.04692569 -0.04700004]
 [-0.04700004 -0.04696578]]
0.01
[[-0.0012785 ]
 [-0.00124399]
 [-0.00018586]
 [-0.00015238]] [[-0.0480759  -0.04799996]
 [-0.04799996 -0.04803495]
 [-0.0479241  -0.04800004]
 [-0.04800004 -0.04796505]]
0.01
[[-0.00130529]
 [-0.00127007]
 [-0.00018958]
 [-0.0001554 ]] [[-0.04907748 -0.04899996]
 [-0.04899996 -0.04903567]
 [-0.04892252 -0.04900004]
 [-0.04900004 -0.04896433]]
0.01
[[-0.00133209]
 [-0.00129615]
 [-0.00019329]
 [-0.00015841]] [[-0.05007906 -0.04999996]
 [-0.04999996 -0.0500364 ]
 [-0.04992

[[-0.00249638]
 [-0.00242961]
 [-0.00034083]
 [-0.00027587]] [[-0.09314703 -0.09299993]
 [-0.09299993 -0.0930677 ]
 [-0.09285297 -0.09300007]
 [-0.09300007 -0.0929323 ]]
0.01
[[-0.00252381]
 [-0.00245633]
 [-0.0003439 ]
 [-0.00027824]] [[-0.09414861 -0.09399992]
 [-0.09399992 -0.09406843]
 [-0.09385139 -0.09400008]
 [-0.09400008 -0.09393157]]
0.01
[[-0.00255127]
 [-0.00248307]
 [-0.00034696]
 [-0.00028059]] [[-0.09515019 -0.09499992]
 [-0.09499992 -0.09506916]
 [-0.09484981 -0.09500008]
 [-0.09500008 -0.09493084]]
0.01
[[-0.00257874]
 [-0.00250983]
 [-0.00034999]
 [-0.00028292]] [[-0.09615177 -0.09599992]
 [-0.09599992 -0.09606989]
 [-0.09584823 -0.09600008]
 [-0.09600008 -0.09593011]]
0.01
[[-0.00260624]
 [-0.00253661]
 [-0.000353  ]
 [-0.00028523]] [[-0.09715335 -0.09699992]
 [-0.09699992 -0.09707061]
 [-0.09684665 -0.09700008]
 [-0.09700008 -0.09692939]]
0.01
[[-0.00263375]
 [-0.00256341]
 [-0.00035599]
 [-0.00028752]] [[-0.09815493 -0.09799992]
 [-0.09799992 -0.09807134]
 [-0.09784

[[0.0039274 ]
 [0.0039115 ]
 [0.00479663]
 [0.00478075]] [[-0.04107255 -0.04103224]
 [-0.04103224 -0.04107241]
 [-0.04092745 -0.04096776]
 [-0.04096776 -0.04092759]]
0.01
[[0.00402312]
 [0.00400684]
 [0.0049137 ]
 [0.00489742]] [[-0.04207432 -0.04203302]
 [-0.04203302 -0.04207418]
 [-0.04192568 -0.04196698]
 [-0.04196698 -0.04192582]]
0.01
[[0.00411883]
 [0.00410216]
 [0.00503076]
 [0.0050141 ]] [[-0.04307609 -0.04303381]
 [-0.04303381 -0.04307594]
 [-0.04292391 -0.04296619]
 [-0.04296619 -0.04292406]]
0.01
[[0.00421454]
 [0.00419748]
 [0.00514784]
 [0.00513079]] [[-0.04407786 -0.0440346 ]
 [-0.0440346  -0.04407771]
 [-0.04392214 -0.0439654 ]
 [-0.0439654  -0.04392229]]
0.01
[[0.00431024]
 [0.00429279]
 [0.00526492]
 [0.00524748]] [[-0.04507963 -0.04503538]
 [-0.04503538 -0.04507947]
 [-0.04492037 -0.04496462]
 [-0.04496462 -0.04492053]]
0.01
[[0.00440594]
 [0.0043881 ]
 [0.005382  ]
 [0.00536418]] [[-0.0460814  -0.04603617]
 [-0.04603617 -0.04608124]
 [-0.0459186  -0.04596383]
 [-0.04

[[0.00851179]
 [0.00847729]
 [0.01042574]
 [0.01039126]] [[-0.08915746 -0.08906995]
 [-0.08906995 -0.08915715]
 [-0.08884254 -0.08893005]
 [-0.08893005 -0.08884285]]
0.01
[[0.00860699]
 [0.0085721 ]
 [0.01054332]
 [0.01050845]] [[-0.09015923 -0.09007074]
 [-0.09007074 -0.09015892]
 [-0.08984077 -0.08992926]
 [-0.08992926 -0.08984108]]
0.01
[[0.00870217]
 [0.0086669 ]
 [0.01066092]
 [0.01062567]] [[-0.091161   -0.09107153]
 [-0.09107153 -0.09116068]
 [-0.090839   -0.09092847]
 [-0.09092847 -0.09083932]]
0.01
[[0.00879734]
 [0.00876167]
 [0.01077854]
 [0.01074289]] [[-0.09216277 -0.09207231]
 [-0.09207231 -0.09216245]
 [-0.09183723 -0.09192769]
 [-0.09192769 -0.09183755]]
0.01
[[0.00889249]
 [0.00885644]
 [0.01089617]
 [0.01086014]] [[-0.09316454 -0.0930731 ]
 [-0.0930731  -0.09316421]
 [-0.09283546 -0.0929269 ]
 [-0.0929269  -0.09283579]]
0.01
[[0.00898762]
 [0.00895118]
 [0.01101382]
 [0.0109774 ]] [[-0.09416631 -0.09407388]
 [-0.09407388 -0.09416598]
 [-0.09383369 -0.09392612]
 [-0.09

In [6]:
# Train the model on testing dataset
A0_list_test = []
A1_list_test = []
for i in range(int(len(data_test.index)/train_window)-1):
    start = i * train_window
    end = start + train_window
    # Run the model
    A0, A1 = G_learning_with_linear_dynamics(start, end, data_test, \
                                             rf, gamma, beta, \
                                             iterations)
    A0_list_test.append(A0)
    A1_list_test.append(A1)

0.01
[[0.00016618]
 [0.00021483]
 [0.00018749]
 [0.00023658]] [[-0.0010021  -0.00100029]
 [-0.00100029 -0.00100156]
 [-0.0009979  -0.00099971]
 [-0.00099971 -0.00099844]]
0.01
[[0.00033291]
 [0.00043023]
 [0.00037441]
 [0.00047261]] [[-0.0020042  -0.00200057]
 [-0.00200057 -0.00200311]
 [-0.0019958  -0.00199943]
 [-0.00199943 -0.00199689]]
0.01
[[0.00049965]
 [0.00064562]
 [0.00056134]
 [0.00070863]] [[-0.00300629 -0.00300086]
 [-0.00300086 -0.00300467]
 [-0.00299371 -0.00299914]
 [-0.00299914 -0.00299533]]
0.01
[[0.00066639]
 [0.00086102]
 [0.00074827]
 [0.00094465]] [[-0.00400839 -0.00400115]
 [-0.00400115 -0.00400623]
 [-0.00399161 -0.00399885]
 [-0.00399885 -0.00399377]]
0.01
[[0.00083313]
 [0.00107642]
 [0.00093519]
 [0.00118067]] [[-0.00501049 -0.00500143]
 [-0.00500143 -0.00500778]
 [-0.00498951 -0.00499857]
 [-0.00499857 -0.00499222]]
0.01
[[0.00099987]
 [0.00129182]
 [0.00112211]
 [0.00141669]] [[-0.00601259 -0.00600172]
 [-0.00600172 -0.00600934]
 [-0.00598741 -0.00599828]
 [

[[0.00866872]
 [0.01119892]
 [0.00972177]
 [0.0122748 ]] [[-0.05210907 -0.05201488]
 [-0.05201488 -0.05208093]
 [-0.05189093 -0.05198512]
 [-0.05198512 -0.05191907]]
0.01
[[0.00883534]
 [0.01141419]
 [0.00990882]
 [0.01251095]] [[-0.05311116 -0.05301517]
 [-0.05301517 -0.05308248]
 [-0.05288884 -0.05298483]
 [-0.05298483 -0.05291752]]
0.01
[[0.00900194]
 [0.01162945]
 [0.01009588]
 [0.0127471 ]] [[-0.05411326 -0.05401545]
 [-0.05401545 -0.05408404]
 [-0.05388674 -0.05398455]
 [-0.05398455 -0.05391596]]
0.01
[[0.00916854]
 [0.01184471]
 [0.01028294]
 [0.01298326]] [[-0.05511536 -0.05501574]
 [-0.05501574 -0.05508559]
 [-0.05488464 -0.05498426]
 [-0.05498426 -0.05491441]]
0.01
[[0.00933513]
 [0.01205996]
 [0.01047002]
 [0.01321943]] [[-0.05611745 -0.05601603]
 [-0.05601603 -0.05608715]
 [-0.05588255 -0.05598397]
 [-0.05598397 -0.05591285]]
0.01
[[0.00950172]
 [0.0122752 ]
 [0.0106571 ]
 [0.01345561]] [[-0.05711955 -0.05701631]
 [-0.05701631 -0.05708871]
 [-0.05688045 -0.05698369]
 [-0.05

[[0.01665429]
 [0.02151991]
 [0.01871205]
 [0.02362185]] [[-0.1002097  -0.10002861]
 [-0.10002861 -0.1001556 ]
 [-0.0997903  -0.09997139]
 [-0.09997139 -0.0998444 ]]
0.01
[[2.51011734e-05]
 [4.61886355e-05]
 [4.63580139e-05]
 [6.84074260e-05]] [[-0.00100257 -0.00100025]
 [-0.00100025 -0.00100166]
 [-0.00099743 -0.00099975]
 [-0.00099975 -0.00099834]]
0.01
[[4.90348658e-05]
 [9.12069143e-05]
 [9.38835088e-05]
 [1.37985209e-04]] [[-0.00200515 -0.00200051]
 [-0.00200051 -0.00200332]
 [-0.00199485 -0.00199949]
 [-0.00199949 -0.00199668]]
0.01
[[7.29715515e-05]
 [1.36228155e-04]
 [1.41406010e-04]
 [2.07560030e-04]] [[-0.00300772 -0.00300076]
 [-0.00300076 -0.00300498]
 [-0.00299228 -0.00299924]
 [-0.00299924 -0.00299502]]
0.01
[[9.69108278e-05]
 [1.81251953e-04]
 [1.88925921e-04]
 [2.77132293e-04]] [[-0.0040103  -0.00400101]
 [-0.00400101 -0.00400664]
 [-0.0039897  -0.00399899]
 [-0.00399899 -0.00399336]]
0.01
[[0.00012085]
 [0.00022628]
 [0.00023644]
 [0.0003467 ]] [[-0.00501287 -0.0050012

[[0.00114948]
 [0.00216149]
 [0.00228057]
 [0.00333912]] [[-0.04812354 -0.04801214]
 [-0.04801214 -0.04807964]
 [-0.04787646 -0.04798786]
 [-0.04798786 -0.04792036]]
0.01
[[0.0011733 ]
 [0.00220641]
 [0.0023282 ]
 [0.0034088 ]] [[-0.04912611 -0.04901239]
 [-0.04901239 -0.0490813 ]
 [-0.04887389 -0.04898761]
 [-0.04898761 -0.0489187 ]]
0.01
[[0.00119713]
 [0.00225131]
 [0.00237583]
 [0.00347849]] [[-0.05012869 -0.05001264]
 [-0.05001264 -0.05008296]
 [-0.04987131 -0.04998736]
 [-0.04998736 -0.04991704]]
0.01
[[0.00122094]
 [0.0022962 ]
 [0.00242348]
 [0.00354819]] [[-0.05113126 -0.0510129 ]
 [-0.0510129  -0.05108462]
 [-0.05086874 -0.0509871 ]
 [-0.0509871  -0.05091538]]
0.01
[[0.00124474]
 [0.00234109]
 [0.00247113]
 [0.0036179 ]] [[-0.05213383 -0.05201315]
 [-0.05201315 -0.05208628]
 [-0.05186617 -0.05198685]
 [-0.05198685 -0.05191372]]
0.01
[[0.00126854]
 [0.00238597]
 [0.0025188 ]
 [0.00368762]] [[-0.0531364  -0.0530134 ]
 [-0.0530134  -0.05308794]
 [-0.0528636  -0.0529866 ]
 [-0.05

[[0.0022807 ]
 [0.00430459]
 [0.00457939]
 [0.00669663]] [[-0.09624702 -0.09602426]
 [-0.09602426 -0.09615926]
 [-0.09575298 -0.09597574]
 [-0.09597574 -0.09584074]]
0.01
[[0.00230389]
 [0.00434887]
 [0.00462765]
 [0.00676695]] [[-0.09724959 -0.09702452]
 [-0.09702452 -0.09716092]
 [-0.09675041 -0.09697548]
 [-0.09697548 -0.09683908]]
0.01
[[0.00232708]
 [0.00439313]
 [0.00467592]
 [0.00683728]] [[-0.09825216 -0.09802477]
 [-0.09802477 -0.09816258]
 [-0.09774784 -0.09797523]
 [-0.09797523 -0.09783742]]
0.01
[[0.00235024]
 [0.00443737]
 [0.00472422]
 [0.00690764]] [[-0.09925473 -0.09902502]
 [-0.09902502 -0.09916424]
 [-0.09874527 -0.09897498]
 [-0.09897498 -0.09883576]]
0.01
[[0.00237338]
 [0.00448159]
 [0.00477254]
 [0.00697802]] [[-0.1002573  -0.10002528]
 [-0.10002528 -0.10016589]
 [-0.0997427  -0.09997472]
 [-0.09997472 -0.09983411]]
0.01
[[-1.57938576e-05]
 [-1.90012164e-05]
 [ 4.47425911e-06]
 [ 1.47889255e-06]] [[-0.00100296 -0.0010004 ]
 [-0.0010004  -0.00100143]
 [-0.00099704 

[[-6.68837370e-04]
 [-7.97266694e-04]
 [ 2.16053431e-04]
 [ 9.63737387e-05]] [[-0.0401184  -0.04001617]
 [-0.04001617 -0.04005703]
 [-0.0398816  -0.03998383]
 [-0.03998383 -0.03994297]]
0.01
[[-6.85626382e-04]
 [-8.17267868e-04]
 [ 2.21522844e-04]
 [ 9.88525883e-05]] [[-0.04112136 -0.04101657]
 [-0.04101657 -0.04105846]
 [-0.04087864 -0.04098343]
 [-0.04098343 -0.04094154]]
0.01
[[-0.00070242]
 [-0.00083727]
 [ 0.000227  ]
 [ 0.00010134]] [[-0.04212432 -0.04201698]
 [-0.04201698 -0.04205988]
 [-0.04187568 -0.04198302]
 [-0.04198302 -0.04194012]]
0.01
[[-0.00071922]
 [-0.00085729]
 [ 0.00023248]
 [ 0.00010383]] [[-0.04312728 -0.04301738]
 [-0.04301738 -0.04306131]
 [-0.04287272 -0.04298262]
 [-0.04298262 -0.04293869]]
0.01
[[-0.00073603]
 [-0.0008773 ]
 [ 0.00023796]
 [ 0.00010632]] [[-0.04413023 -0.04401779]
 [-0.04401779 -0.04406273]
 [-0.04386977 -0.04398221]
 [-0.04398221 -0.04393727]]
0.01
[[-0.00075284]
 [-0.00089733]
 [ 0.00024345]
 [ 0.00010882]] [[-0.04513319 -0.04501819]
 [-0.

[[-0.00148439]
 [-0.00176708]
 [ 0.00048826]
 [ 0.00022512]] [[-0.0882604  -0.08803556]
 [-0.08803556 -0.08812545]
 [-0.0877396  -0.08796444]
 [-0.08796444 -0.08787455]]
0.01
[[-0.00150168]
 [-0.00178759]
 [ 0.00049424]
 [ 0.0002281 ]] [[-0.08926336 -0.08903596]
 [-0.08903596 -0.08912687]
 [-0.08873664 -0.08896404]
 [-0.08896404 -0.08887313]]
0.01
[[-0.00151899]
 [-0.00180811]
 [ 0.00050022]
 [ 0.0002311 ]] [[-0.09026631 -0.09003637]
 [-0.09003637 -0.0901283 ]
 [-0.08973369 -0.08996363]
 [-0.08996363 -0.0898717 ]]
0.01
[[-0.00153631]
 [-0.00182865]
 [ 0.00050623]
 [ 0.00023412]] [[-0.09126927 -0.09103677]
 [-0.09103677 -0.09112972]
 [-0.09073073 -0.09096323]
 [-0.09096323 -0.09087028]]
0.01
[[-0.00155365]
 [-0.00184921]
 [ 0.00051225]
 [ 0.00023716]] [[-0.09227223 -0.09203717]
 [-0.09203717 -0.09213115]
 [-0.09172777 -0.09196283]
 [-0.09196283 -0.09186885]]
0.01
[[-0.00157101]
 [-0.00186978]
 [ 0.00051829]
 [ 0.00024021]] [[-0.09327519 -0.09303758]
 [-0.09303758 -0.09313257]
 [-0.09272

[[0.0019154 ]
 [0.00159651]
 [0.0024537 ]
 [0.00214163]] [[-0.03617655 -0.03603203]
 [-0.03603203 -0.03611077]
 [-0.03582345 -0.03596797]
 [-0.03596797 -0.03588923]]
0.01
[[0.00196868]
 [0.00164093]
 [0.00252178]
 [0.00220105]] [[-0.03718145 -0.03703292]
 [-0.03703292 -0.03711385]
 [-0.03681855 -0.03696708]
 [-0.03696708 -0.03688615]]
0.01
[[0.00202196]
 [0.00168535]
 [0.00258986]
 [0.00226046]] [[-0.03818635 -0.03803381]
 [-0.03803381 -0.03811693]
 [-0.03781365 -0.03796619]
 [-0.03796619 -0.03788307]]
0.01
[[0.00207524]
 [0.00172978]
 [0.00265794]
 [0.00231988]] [[-0.03919125 -0.0390347 ]
 [-0.0390347  -0.03912   ]
 [-0.03880875 -0.0389653 ]
 [-0.0389653  -0.03888   ]]
0.01
[[0.00212852]
 [0.0017742 ]
 [0.00272602]
 [0.00237929]] [[-0.04019616 -0.04003559]
 [-0.04003559 -0.04012308]
 [-0.03980384 -0.03996441]
 [-0.03996441 -0.03987692]]
0.01
[[0.0021818 ]
 [0.00181862]
 [0.00279411]
 [0.00243871]] [[-0.04120106 -0.04103647]
 [-0.04103647 -0.04112615]
 [-0.04079894 -0.04096353]
 [-0.04

[[0.00446936]
 [0.00372519]
 [0.00572519]
 [0.00499714]] [[-0.08441174 -0.08407468]
 [-0.08407468 -0.08425839]
 [-0.08358826 -0.08392532]
 [-0.08392532 -0.08374161]]
0.01
[[0.00452242]
 [0.00376939]
 [0.00579349]
 [0.00505678]] [[-0.08541664 -0.08507556]
 [-0.08507556 -0.08526146]
 [-0.08458336 -0.08492444]
 [-0.08492444 -0.08473854]]
0.01
[[0.00457548]
 [0.00381358]
 [0.0058618 ]
 [0.00511642]] [[-0.08642154 -0.08607645]
 [-0.08607645 -0.08626454]
 [-0.08557846 -0.08592355]
 [-0.08592355 -0.08573546]]
0.01
[[0.00462853]
 [0.00385777]
 [0.00593011]
 [0.00517607]] [[-0.08742644 -0.08707734]
 [-0.08707734 -0.08726761]
 [-0.08657356 -0.08692266]
 [-0.08692266 -0.08673239]]
0.01
[[0.00468156]
 [0.00390195]
 [0.00599844]
 [0.00523573]] [[-0.08843133 -0.08807823]
 [-0.08807823 -0.08827068]
 [-0.08756867 -0.08792177]
 [-0.08792177 -0.08772932]]
0.01
[[0.00473459]
 [0.00394611]
 [0.00606677]
 [0.0052954 ]] [[-0.08943623 -0.08907912]
 [-0.08907912 -0.08927376]
 [-0.08856377 -0.08892088]
 [-0.08

[[0.00131289]
 [0.00112938]
 [0.0020831 ]
 [0.00189948]] [[-0.03207242 -0.03202203]
 [-0.03202203 -0.03205223]
 [-0.03192758 -0.03197797]
 [-0.03197797 -0.03194777]]
0.01
[[0.00135383]
 [0.00116458]
 [0.00214829]
 [0.00195892]] [[-0.03307469 -0.03302272]
 [-0.03302272 -0.03305386]
 [-0.03292531 -0.03297728]
 [-0.03297728 -0.03294614]]
0.01
[[0.00139476]
 [0.00119978]
 [0.00221348]
 [0.00201838]] [[-0.03407695 -0.03402341]
 [-0.03402341 -0.03405549]
 [-0.03392305 -0.03397659]
 [-0.03397659 -0.03394451]]
0.01
[[0.00143569]
 [0.00123498]
 [0.00227867]
 [0.00207783]] [[-0.03507921 -0.03502409]
 [-0.03502409 -0.03505712]
 [-0.03492079 -0.03497591]
 [-0.03497591 -0.03494288]]
0.01
[[0.00147662]
 [0.00127017]
 [0.00234387]
 [0.0021373 ]] [[-0.03608148 -0.03602478]
 [-0.03602478 -0.03605875]
 [-0.03591852 -0.03597522]
 [-0.03597522 -0.03594125]]
0.01
[[0.00151754]
 [0.00130535]
 [0.00240908]
 [0.00219676]] [[-0.03708374 -0.03702547]
 [-0.03702547 -0.03706038]
 [-0.03691626 -0.03697453]
 [-0.03

[[0.0032691 ]
 [0.00281027]
 [0.00522087]
 [0.00476187]] [[-0.08018102 -0.08005505]
 [-0.08005505 -0.08013054]
 [-0.07981898 -0.07994495]
 [-0.07994495 -0.07986946]]
0.01
[[0.00330957]
 [0.002845  ]
 [0.00528653]
 [0.00482179]] [[-0.08118328 -0.08105574]
 [-0.08105574 -0.08113217]
 [-0.08081672 -0.08094426]
 [-0.08094426 -0.08086783]]
0.01
[[0.00335002]
 [0.00287971]
 [0.0053522 ]
 [0.00488173]] [[-0.08218554 -0.08205643]
 [-0.08205643 -0.0821338 ]
 [-0.08181446 -0.08194357]
 [-0.08194357 -0.0818662 ]]
0.01
[[0.00339045]
 [0.00291441]
 [0.00541789]
 [0.00494168]] [[-0.0831878  -0.08305711]
 [-0.08305711 -0.08313543]
 [-0.0828122  -0.08294289]
 [-0.08294289 -0.08286457]]
0.01
[[0.00343087]
 [0.00294909]
 [0.0054836 ]
 [0.00500165]] [[-0.08419007 -0.0840578 ]
 [-0.0840578  -0.08413706]
 [-0.08380993 -0.0839422 ]
 [-0.0839422  -0.08386294]]
0.01
[[0.00347127]
 [0.00298376]
 [0.00554932]
 [0.00506164]] [[-0.08519233 -0.08505849]
 [-0.08505849 -0.0851387 ]
 [-0.08480767 -0.08494151]
 [-0.08

# Backtesting

In [7]:
# Backtesting: Clean the result and calculate the returns
returns_result = data_test.copy().iloc[train_window:,range(N)]

# Create columns
for i in range(N):
    returns_result['money in '+str(i)] = 0.5
returns_result['risk-free asset value'] = 1
returns_result['Portfolio Value'] = 0

# Some variables for convenience
I = np.identity(N)
In = np.concatenate((I,-I))
x = []
x_before_return = []
for t in range(len(returns_result.index)):
    x.append(np.array([[1/N]]*N))
    x_before_return.append(np.array([[1/N]]*N))

for t in range(len(returns_result.index)):
    j = int(t/train_window)
    k = t - j * train_window
    
    # Write the money invested to the testing dataset
    if (k>0):
        x_before_return[t]=x[t-1]+np.dot(In.T, A0_list_test[j][k-1]+\
                                         np.dot(A1_list_test[j][k-1],\
                                                x[t-1]))
        for i in range(N): 
            x[t][i] = (1+returns_result.iloc[t,i]) * \
                      x_before_return[t][i]
            returns_result.loc[returns_result.index[t],\
                               'money in '+str(i)] = x[t][i]
    # Calculate portfolio values and risk-free asset value
    if (t==0):
        returns_result.loc[returns_result.index[t],\
                           'Portfolio Value'] = 1
        returns_result.loc[returns_result.index[t],\
                           'risk-free asset value'] = 0
    else:
        returns_result.loc[returns_result.index[t],'risk-free asset value'] = \
            (returns_result.loc[returns_result.index[t-1],'Portfolio Value']-x_before_return[t].sum())*(1+rf)
        returns_result.loc[returns_result.index[t],'Portfolio Value'] = \
            x[t].sum() + returns_result.loc[returns_result.index[t],'risk-free asset value']

# Calculate daily return
returns_result['Daily return'] =  returns_result['Portfolio Value']/\
                            returns_result['Portfolio Value'].shift(1)
# Calculate allocation weights
for i in range(N):
    returns_result['w'+str(i)] = returns_result['money in '+str(i)]/\
                            returns_result['Portfolio Value']


In [8]:
returns_result.head()

AAPL      GOOG  money in 0  money in 1  risk-free asset value  \
Date                                                                            
2018-04-12  0.009859  0.012295    0.500000    0.500000               0.000000   
2018-04-13  0.003388 -0.003138    0.502318    0.499146              -0.001339   
2018-04-16  0.006238  0.008462    0.506090    0.504107              -0.002705   
2018-04-17  0.013764  0.034856    0.513625    0.522297              -0.003865   
2018-04-18 -0.002244 -0.001936    0.513128    0.522048              -0.005285   

            Portfolio Value  Daily return        w0        w1  
Date                                                           
2018-04-12         1.000000           NaN  0.500000  0.500000  
2018-04-13         1.000125      1.000125  0.502255  0.499083  
2018-04-16         1.007492      1.007367  0.502326  0.500358  
2018-04-17         1.032058      1.024383  0.497671  0.506073  
2018-04-18         1.029890      0.997900  0.498235  0.506896

In [9]:
returns_result.tail()

AAPL      GOOG  money in 0  money in 1  risk-free asset value  \
Date                                                                            
2019-07-08 -0.020614 -0.013468    0.536922    0.492406               0.192565   
2019-07-09  0.006099  0.007596    0.540748    0.496771               0.191408   
2019-07-10  0.009889  0.013913    0.546534    0.504222               0.190452   
2019-07-11 -0.007282  0.003271    0.543087    0.506476               0.189323   
2019-07-12  0.007683  0.000603    0.544460    0.504078               0.194813   

            Portfolio Value  Daily return        w0        w1  
Date                                                           
2019-07-08         1.221893      0.985472  0.439418  0.402986  
2019-07-09         1.228927      1.005756  0.440016  0.404232  
2019-07-10         1.241208      1.009993  0.440325  0.406235  
2019-07-11         1.238885      0.998129  0.438367  0.408816  
2019-07-12         1.243351      1.003604  0.437898  0.405419

In [10]:
returns_result.to_csv('Continuous G-learning.csv')

In [ ]:
#######################################################################